version: 2
jobs:
  build:
    working_directory: ~/mytindy
    docker:
      - image: circleci/node:16
    steps:
      - checkout
      - run: 
          name: update-npm
          command: "sudo npm install -g npm@8"
      - restore_cache:
          key: AngularCircleCI-{{ .Branch }}-{{ checksum "package.json" }}
      - run:
          name: install-packages
          command: npm install 
      - save_cache:
          key: AngularCircleCI-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - "./node_modules"
      - run:
         name: test
         command: npm run test